//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/PixelStarcraft.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GamePlayer")]
  public partial class GamePlayer : global::ProtoBuf.IExtensible
  {
    public GamePlayer() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private bool _isHuman = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isHuman", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isHuman
    {
      get { return _isHuman; }
      set { _isHuman = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Dictionary")]
  public partial class Dictionary : global::ProtoBuf.IExtensible
  {
    public Dictionary() {}
    
    private uint _key = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleData")]
  public partial class BattleData : global::ProtoBuf.IExtensible
  {
    public BattleData() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.Dictionary> _troops = new global::System.Collections.Generic.List<usercmd.Dictionary>();
    [global::ProtoBuf.ProtoMember(1, Name=@"troops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.Dictionary> troops
    {
      get { return _troops; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChooseCal")]
  public partial class ChooseCal : global::ProtoBuf.IExtensible
  {
    public ChooseCal() {}
    
    private bool _isCal = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isCal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isCal
    {
      get { return _isCal; }
      set { _isCal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleResult")]
  public partial class BattleResult : global::ProtoBuf.IExtensible
  {
    public BattleResult() {}
    
    private uint _roundNum = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private bool _isWin = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isWin
    {
      get { return _isWin; }
      set { _isWin = value; }
    }
    private bool _isFinished = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isFinished", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFinished
    {
      get { return _isFinished; }
      set { _isFinished = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.Dictionary> _makeDamage = new global::System.Collections.Generic.List<usercmd.Dictionary>();
    [global::ProtoBuf.ProtoMember(3, Name=@"makeDamage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.Dictionary> makeDamage
    {
      get { return _makeDamage; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.Dictionary> _takeDamage = new global::System.Collections.Generic.List<usercmd.Dictionary>();
    [global::ProtoBuf.ProtoMember(4, Name=@"takeDamage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.Dictionary> takeDamage
    {
      get { return _takeDamage; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgType_wzb")]
    public enum MsgType_wzb
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"login_REQ", Value=0)]
      login_REQ = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"login_CNF", Value=1)]
      login_CNF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"match_REQ", Value=2)]
      match_REQ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"match_CNF", Value=3)]
      match_CNF = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"action_REQ", Value=4)]
      action_REQ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"action_CNF", Value=5)]
      action_CNF = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"action", Value=6)]
      action = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"deactiv_REQ", Value=7)]
      deactiv_REQ = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"deactiv_CNF", Value=8)]
      deactiv_CNF = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"reserved1", Value=9)]
      reserved1 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"reserved2", Value=10)]
      reserved2 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"reserved3", Value=11)]
      reserved3 = 11
    }
  
}