//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: footMan.proto
namespace _footMan_client_
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"_Human_")]
  public partial class _Human_ : global::ProtoBuf.IExtensible
  {
    public _Human_() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private uint _attack = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private uint _defence = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private uint _heart = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"heart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint heart
    {
      get { return _heart; }
      set { _heart = value; }
    }
    private uint _speed = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private bool _spec = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"spec", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool spec
    {
      get { return _spec; }
      set { _spec = value; }
    }
    private uint _chDef = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"chDef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chDef
    {
      get { return _chDef; }
      set { _chDef = value; }
    }
    private uint _chDefVal = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chDefVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chDefVal
    {
      get { return _chDefVal; }
      set { _chDefVal = value; }
    }
    private uint _chAtk = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"chAtk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chAtk
    {
      get { return _chAtk; }
      set { _chAtk = value; }
    }
    private uint _chAtkVal = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"chAtkVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chAtkVal
    {
      get { return _chAtkVal; }
      set { _chAtkVal = value; }
    }
    private uint _extraDmg = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"extraDmg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint extraDmg
    {
      get { return _extraDmg; }
      set { _extraDmg = value; }
    }
    private uint _extraDmgVal = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"extraDmgVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint extraDmgVal
    {
      get { return _extraDmgVal; }
      set { _extraDmgVal = value; }
    }
    private uint _cost = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cost
    {
      get { return _cost; }
      set { _cost = value; }
    }
    private uint _maxNum = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"_Demon_")]
  public partial class _Demon_ : global::ProtoBuf.IExtensible
  {
    public _Demon_() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private uint _attack = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private uint _defence = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private uint _heart = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"heart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint heart
    {
      get { return _heart; }
      set { _heart = value; }
    }
    private uint _speed = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private bool _spec = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"spec", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool spec
    {
      get { return _spec; }
      set { _spec = value; }
    }
    private uint _chDef = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"chDef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chDef
    {
      get { return _chDef; }
      set { _chDef = value; }
    }
    private uint _chDefVal = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chDefVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chDefVal
    {
      get { return _chDefVal; }
      set { _chDefVal = value; }
    }
    private uint _chAtk = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"chAtk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chAtk
    {
      get { return _chAtk; }
      set { _chAtk = value; }
    }
    private uint _chAtkVal = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"chAtkVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chAtkVal
    {
      get { return _chAtkVal; }
      set { _chAtkVal = value; }
    }
    private uint _extraDmg = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"extraDmg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint extraDmg
    {
      get { return _extraDmg; }
      set { _extraDmg = value; }
    }
    private uint _extraDmgVal = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"extraDmgVal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint extraDmgVal
    {
      get { return _extraDmgVal; }
      set { _extraDmgVal = value; }
    }
    private uint _cost = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cost
    {
      get { return _cost; }
      set { _cost = value; }
    }
    private uint _maxNum = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"_Excel_")]
  public partial class _Excel_ : global::ProtoBuf.IExtensible
  {
    public _Excel_() {}
    
    private readonly global::System.Collections.Generic.List<_footMan_client_._Human_> _HumanData = new global::System.Collections.Generic.List<_footMan_client_._Human_>();
    [global::ProtoBuf.ProtoMember(1, Name=@"HumanData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<_footMan_client_._Human_> HumanData
    {
      get { return _HumanData; }
    }
  
    private readonly global::System.Collections.Generic.List<_footMan_client_._Demon_> _DemonData = new global::System.Collections.Generic.List<_footMan_client_._Demon_>();
    [global::ProtoBuf.ProtoMember(2, Name=@"DemonData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<_footMan_client_._Demon_> DemonData
    {
      get { return _DemonData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}